music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    #/music/
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
     path('album/add/', views.CreateView.as_view(), name='album-add'),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [

    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

music/models.py
from django.db import models
from django.urls import reverse

class Albums(models.Model):

    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)
    def get_absolute_url(self):
        return reverse('music:detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + '-' + self.artist

class Song(models.Model):

    album = models.ForeignKey(Albums, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .models import Albums

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'
    def get_queryset(self):
        return Albums.objects.all()

class DetailView(generic.DetailView):
    model = Albums
    template_name = 'music/detail.html'

class AlbumsCreate(CreateView):
    model = Albums
    filter = ['artist', 'album_title', 'genre', 'album_logo']

music/templates/music/albums_form.html
{% extends "music/base.html" %}
{% block title %}Add a new Album{% endblock %}
{% block albums_active %}Active{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My music{% endblock %}</title>
    {% load staticfiles %}
<link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Satisfy" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'music/style2.css' %}">


</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">My Music</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav" >
                <li class="active" >
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                    </a>
                </li>
                 <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Song
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right" >
                <li class="" >
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Albums
                    </a>
                </li>
                 <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}

{% endblock %}
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album details{% endblock %}
{% block body %}
<img src="{{ albums.album_logo }}" style="width: 250px;">
<h1>{{ albums.album_title  }}</h1>
<h2>{{ albums.artist }}</h2>

{% if error_message %}
    <p><strong>{{ error_massage }}</strong></p>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    {% for song in albums.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="https://cdn4.iconfinder.com/data/icons/small-n-flat/24/star-24.png">
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-ofoset-2 col-sm-10">
            <span class="text-danger small">{{ field.error }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}
{% if all_albums %}
    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>khong co gi cung a</h3>
{% endif %}
{% endblock %}